use crate::{
    lock_guard::LockGuard,
    new_types::{BitMask, MAX_SHARDS, ShardCount, ShardIndex},
    shard::Shard,
};
use crossbeam_utils::CachePadded;
use hashbrown::HashTable;
use portable_atomic::{AtomicU128, Ordering};
use std::cell::UnsafeCell;

/// Internal store of the map's shards.
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
pub struct Custodian<K, V> {
    pub(crate) shard_count: ShardCount,
    pub(crate) shards: Vec<CachePadded<UnsafeCell<Shard<K, V>>>>,
    pub(crate) locked_mask: AtomicU128,
}

// SAFETY: shard access is serialised by `locked_mask`. A shard is only
// borrowed while its bit is set in the mask, so no two threads can hold
// aliasing `&mut` references to the same shard. Sharing `&Custodian` across
// threads is therefore sound when the shard contents are `Send + Sync`.
unsafe impl<K, V> Sync for Custodian<K, V>
where
    K: Send + Sync,
    V: Send + Sync,
{
}

/// Exponential backoff used by the CAS loops.
#[inline]
fn backoff(spins: &mut u32) {
    if *spins < 6 {
        for _ in 0..(1u32 << *spins) {
            std::hint::spin_loop();
        }
    } else if *spins < 10 {
        std::thread::yield_now();
    } else {
        std::thread::park_timeout(std::time::Duration::from_micros(50));
    }
    *spins = spins.saturating_add(1);
}

impl<K, V> Custodian<K, V> {
    pub(crate) fn new(shard_count: ShardCount, capacity: usize) -> Self {
        debug_assert!(shard_count.0 as usize <= MAX_SHARDS);
        let mut shards = Vec::with_capacity(shard_count.0 as usize);
        let capacity_per_shard = capacity.div_ceil(shard_count.0 as usize);
        for _ in 0..shard_count.0 {
            shards.push(CachePadded::new(UnsafeCell::new(HashTable::with_capacity(
                capacity_per_shard,
            ))));
        }
        Self {
            shard_count,
            shards,
            locked_mask: AtomicU128::new(0),
        }
    }

    pub(crate) fn from_shards(
        shard_count: ShardCount,
        shards: Vec<CachePadded<UnsafeCell<Shard<K, V>>>>,
    ) -> Self {
        Self {
            shard_count,
            shards,
            locked_mask: AtomicU128::new(0),
        }
    }

    /// Acquires every shard named in `needed`, all-or-nothing.
    pub(crate) fn acquire(&self, needed: BitMask) {
        if needed == BitMask::ZERO {
            return;
        }
        let mut spins = 0u32;
        loop {
            let cur = BitMask(self.locked_mask.load(Ordering::Acquire));
            if cur & needed == BitMask::ZERO
                && self
                    .locked_mask
                    .compare_exchange_weak(
                        cur.0,
                        (cur | needed).0,
                        Ordering::AcqRel,
                        Ordering::Acquire,
                    )
                    .is_ok()
            {
                return;
            }
            backoff(&mut spins);
        }
    }

    pub(crate) fn release(&self, mask: BitMask) {
        if mask == BitMask::ZERO {
            return;
        }
        self.locked_mask.fetch_and(!mask.0, Ordering::AcqRel);
    }

    pub(crate) fn guard_at(&self, shard_index: ShardIndex) -> LockGuard<'_, K, V> {
        self.lock_guard(shard_index.bitmask())
    }

    /// Acquires every shard named by `mask` and returns a guard that releases
    /// them on drop.
    pub fn lock_guard(&self, mask: BitMask) -> LockGuard<'_, K, V> {
        self.acquire(mask);
        LockGuard {
            locked_mask: mask,
            custodian: self,
        }
    }
}
