use crate::{
    lock_guards::LockGuards,
    lock_policies::lock_policy::LockPolicy,
    new_types::{BitMask, MAX_SHARDS, ShardCount, ShardIndex},
    shard::Shard,
};
use crossbeam_utils::CachePadded;
use hashbrown::HashTable;
use portable_atomic::{AtomicU128, Ordering};
use std::{
    marker::PhantomData,
    ops::{Deref, DerefMut},
};

/// Internal store of the map's shards.
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
pub struct Custodian<K, V, L>
where
    L: LockPolicy,
{
    pub(crate) shard_count: ShardCount,
    pub(crate) shards: Vec<CachePadded<L::Lock<Shard<K, V>>>>,
    pub(crate) locked_mask: AtomicU128,
    pub(crate) _marker: PhantomData<L>,
}

unsafe impl<K, V, L> Sync for Custodian<K, V, L>
where
    K: Send + Sync,
    V: Send + Sync,
    L: LockPolicy,
    L::Lock<Shard<K, V>>: Send,
{
}

/// Exponential backoff used by the CAS loops.
#[inline]
fn backoff(spins: &mut u32) {
    if *spins < 6 {
        for _ in 0..(1u32 << *spins) {
            std::hint::spin_loop();
        }
    } else if *spins < 10 {
        std::thread::yield_now();
    } else {
        std::thread::park_timeout(std::time::Duration::from_micros(50));
    }
    *spins = spins.saturating_add(1);
}

impl<K, V, L> Custodian<K, V, L>
where
    L: LockPolicy,
{
    pub(crate) fn new(shard_count: ShardCount, capacity: usize) -> Self {
        debug_assert!(shard_count.0 as usize <= MAX_SHARDS);
        let mut shards = Vec::with_capacity(shard_count.0 as usize);
        let capacity_per_shard = capacity.div_ceil(shard_count.0 as usize);
        for _ in 0..shard_count.0 {
            shards.push(CachePadded::new(L::new(HashTable::with_capacity(
                capacity_per_shard,
            ))));
        }
        Self {
            shard_count,
            shards,
            locked_mask: AtomicU128::new(0),
            _marker: PhantomData,
        }
    }

    pub(crate) fn from_shards(
        shard_count: ShardCount,
        shards: Vec<CachePadded<L::Lock<Shard<K, V>>>>,
    ) -> Self {
        Self {
            shard_count,
            shards,
            locked_mask: AtomicU128::new(0),
            _marker: PhantomData,
        }
    }

    /// Acquires every shard named in `needed`, all-or-nothing.
    pub(crate) fn acquire(&self, needed: u128) {
        if needed == 0 {
            return;
        }
        let mut spins = 0u32;
        loop {
            let cur = self.locked_mask.load(Ordering::Acquire);
            if cur & needed == 0
                && self
                    .locked_mask
                    .compare_exchange_weak(cur, cur | needed, Ordering::AcqRel, Ordering::Acquire)
                    .is_ok()
            {
                return;
            }
            backoff(&mut spins);
        }
    }

    pub(crate) fn release(&self, mask: u128) {
        if mask == 0 {
            return;
        }
        self.locked_mask.fetch_and(!mask, Ordering::AcqRel);
    }

    /// Acquires read/write guards for the given shard bitmasks.
    pub fn lock_guards(&self, read: BitMask, write: BitMask) -> LockGuards<'_, K, V, L> {
        let needed = (read | write).0;
        self.acquire(needed);

        let mut read_guards = std::array::from_fn(|_| None);
        let mut write_guards = std::array::from_fn(|_| None);

        let mut bits = needed;
        while bits != 0 {
            let i = bits.trailing_zeros() as usize;
            bits &= bits - 1;
            let shard_lock = &self.shards[i];
            let bit = BitMask(1u128 << i);
            if (write & bit) != BitMask::ZERO {
                write_guards[i] = Some(L::write(shard_lock));
            } else {
                read_guards[i] = Some(L::read(shard_lock));
            }
        }
        LockGuards {
            read: read_guards,
            write: write_guards,
            write_bitmask: write,
            custodian: self,
            locked_mask: needed,
        }
    }

    pub(crate) fn write_guards(&self, write: BitMask) -> LockGuards<'_, K, V, L> {
        self.lock_guards(BitMask::ZERO, write)
    }

    pub(crate) fn read_guard_at(&self, shard_index: ShardIndex) -> ReadGuardAt<'_, K, V, L> {
        let mask = shard_index.bitmask().0;
        self.acquire(mask);
        let shard_lock = &self.shards[shard_index.0 as usize];
        ReadGuardAt {
            custodian: self,
            mask,
            guard: L::read(shard_lock),
        }
    }

    pub(crate) fn write_guard_at(&self, shard_index: ShardIndex) -> WriteGuardAt<'_, K, V, L> {
        let mask = shard_index.bitmask().0;
        self.acquire(mask);
        let shard_lock = &self.shards[shard_index.0 as usize];
        WriteGuardAt {
            custodian: self,
            mask,
            guard: L::write(shard_lock),
        }
    }
}

pub(crate) struct ReadGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    custodian: &'a Custodian<K, V, L>,
    mask: u128,
    guard: L::ReadGuard<'a, Shard<K, V>>,
}

impl<'a, K, V, L> Drop for ReadGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    fn drop(&mut self) {
        self.custodian.release(self.mask);
    }
}

impl<'a, K, V, L> Deref for ReadGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    type Target = Shard<K, V>;

    fn deref(&self) -> &Self::Target {
        &self.guard
    }
}

pub(crate) struct WriteGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    custodian: &'a Custodian<K, V, L>,
    mask: u128,
    guard: L::WriteGuard<'a, Shard<K, V>>,
}

impl<'a, K, V, L> Drop for WriteGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    fn drop(&mut self) {
        self.custodian.release(self.mask);
    }
}

impl<'a, K, V, L> Deref for WriteGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    type Target = Shard<K, V>;

    fn deref(&self) -> &Self::Target {
        &self.guard
    }
}

impl<'a, K, V, L> DerefMut for WriteGuardAt<'a, K, V, L>
where
    K: 'a,
    V: 'a,
    L: LockPolicy + 'a,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.guard
    }
}
