use crate::new_types::{HashCode, ShardIndex};

/// A key together with its pre-computed hash and shard index.
///
/// Created internally by [`Indexer::indexed_key`](crate::indexer::Indexer::indexed_key). Used throughout
/// the transaction system to avoid re-hashing.
///
/// The `Hash`, `Eq`, `PartialEq`, `Clone` and `Debug` impls (and their `K`
/// bounds) are generated by the derives below; the struct itself can be
/// formed for any `K`.
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct TxKey<K> {
    /// Pre-computed hash code of the key.
    pub hash_code: HashCode,
    /// The shard this key belongs to.
    pub shard_index: ShardIndex,
    /// Version of the routed leaf at the time the key was indexed.
    ///
    /// Used as a staleness check: if the leaf's version changed before the
    /// transaction acquired its locks, the routing is retried.
    pub version: u32,
    /// The original key value.
    pub key: K,
}
