use crate::{
    key::TxKey, new_types::BitMask, new_types::MAX_SHARDS, result::MISSING_LOCK_GUARD_ERROR,
    shard::Shard, shard_map::MaskGuard,
};

/// Guards for the shards locked during a prepared transaction execution.
///
/// The CAS lock mask is the only lock; these fields are plain references into
/// the (never-moving) leaf slots that are valid only while `_mask` is held.
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
pub struct LockGuards<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    pub read: [Option<&'ex Shard<K, V>>; MAX_SHARDS],
    pub write: [Option<&'ex mut Shard<K, V>>; MAX_SHARDS],
    pub write_bitmask: BitMask,
    /// Keeps the leaf mask acquired by the transaction alive until the guards
    /// are dropped.
    pub(crate) _mask: MaskGuard<'ex, Shard<K, V>>,
}

impl<'ex, K, V> LockGuards<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    pub fn read_guard(&self, key: &TxKey<K>) -> &'ex Shard<K, V> {
        self.read[key.shard_index.0 as usize].expect(MISSING_LOCK_GUARD_ERROR)
    }
    pub fn write_guard(&mut self, key: &TxKey<K>) -> &mut Shard<K, V> {
        self.write[key.shard_index.0 as usize]
            .as_mut()
            .expect(MISSING_LOCK_GUARD_ERROR)
    }
}
