use crate::{
    custodian::Custodian,
    key::TxKey,
    new_types::{BitMask, ShardIndex},
    shard::Shard,
};
use std::ops::{Deref, DerefMut};

/// RAII guard for the shards locked during a transaction execution.
///
/// The guard only tracks which shard indexes are locked and borrows the
/// custodian so any locked shard can be fetched on demand. Releasing the
/// shards happens in [`Drop`].
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
pub struct LockGuard<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    pub(crate) locked_mask: BitMask,
    pub(crate) custodian: &'ex Custodian<K, V>,
}

impl<'ex, K, V> Drop for LockGuard<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    fn drop(&mut self) {
        self.custodian.release(self.locked_mask);
    }
}

impl<'ex, K, V> LockGuard<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    /// Fetches the shard at `shard_index` from the custodian.
    pub fn shard(&self, shard_index: ShardIndex) -> &mut Shard<K, V> {
        debug_assert!(self.locked_mask & shard_index.bitmask() != BitMask::ZERO);
        // SAFETY: the index is part of `locked_mask`, which the custodian
        // acquired exclusively, and `&mut self` prevents aliasing borrows
        // through this guard for the lifetime of the returned reference.
        unsafe { &mut *self.custodian.shards[shard_index.0 as usize].get() }
    }

    /// Fetches the shard the key lives on.
    pub fn shard_for_key(&self, key: &TxKey<K>) -> &mut Shard<K, V> {
        self.shard(key.shard_index)
    }

    /// The index of the single shard held by a per-shard guard.
    fn single_shard_index(&self) -> ShardIndex {
        ShardIndex(self.locked_mask.trailing_zeros() as u8)
    }
}

impl<'ex, K, V> Deref for LockGuard<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    type Target = Shard<K, V>;

    /// Fetches the single shard held by this guard.
    fn deref(&self) -> &Self::Target {
        let shard_index = self.single_shard_index();
        debug_assert!(self.locked_mask & shard_index.bitmask() != BitMask::ZERO);
        // SAFETY: the index is part of `locked_mask`, which the custodian
        // acquired exclusively, so no other thread can access this shard
        // while the guard is alive.
        unsafe { &*self.custodian.shards[shard_index.0 as usize].get() }
    }
}

impl<'ex, K, V> DerefMut for LockGuard<'ex, K, V>
where
    K: 'ex,
    V: 'ex,
{
    /// Fetches the single shard held by this guard.
    fn deref_mut(&mut self) -> &mut Self::Target {
        let shard_index = self.single_shard_index();
        self.shard(shard_index)
    }
}
