use crate::{
    key::TxKey, lock_guards::LockGuards, lock_policies::lock_policy::LockPolicy,
    new_types::BitMask, prepared::schema::TxKeySelector, shard_ops::ShardOps,
};
use std::{
    marker::PhantomData,
    ops::{Deref, DerefMut},
};

/// Internal guard precondition for a prepared transaction.
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
pub struct PreparedGuard<'tx, K, V, KEYS, PARAMS, STATE> {
    pub name: String,
    pub key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
    #[allow(clippy::type_complexity)]
    pub condition: Box<dyn Fn(&K, Option<&V>, &PARAMS, &mut STATE) -> bool + 'tx>,
    pub _phantom: PhantomData<STATE>,
}

impl<'tx, K, V, KEYS, PARAMS, STATE> PreparedGuard<'tx, K, V, KEYS, PARAMS, STATE> {
    /// Bitmask of the shard the guard's key lives on.
    pub fn read_bitmask(&self, keys: &KEYS) -> BitMask {
        let key = self.key_selector.get(keys);
        key.shard_index.bitmask()
    }
}

impl<'tx, K, V, KEYS, PARAMS, STATE> PreparedGuard<'tx, K, V, KEYS, PARAMS, STATE>
where
    K: Eq,
{
    /// Checks the guard's condition against the locked shards.
    pub fn is_condition_met<L>(
        &self,
        lock_guards: &mut LockGuards<'_, K, V, L>,
        keys: &KEYS,
        params: &PARAMS,
        state: &mut STATE,
    ) -> bool
    where
        L: LockPolicy,
    {
        let key = self.key_selector.get(keys);
        let shard = if (key.shard_index.bitmask() & lock_guards.write_bitmask) != BitMask::ZERO {
            lock_guards.write_guard(key).deref_mut()
        } else {
            lock_guards.read_guard(key).deref()
        };
        let value_ref = ShardOps::value_ref(shard, key.hash_code, &key.key);
        (self.condition)(&key.key, value_ref, params, state)
    }
}
