use crate::{
    indexer::Indexer, key::TxKey, lock_guards::LockGuards, lock_policies::lock_policy::LockPolicy,
    multi_shard_ops::MultiShardOps, new_types::BitMask, prepared::schema::TxKeySelector,
    shard_ops::ShardOps,
};
use hashbrown::HashSet;
use std::{
    hash::{BuildHasher, Hash},
    ops::{Deref, DerefMut},
};

/// Internal operation of a prepared transaction.
///
/// Exposed so the prepared transaction types generated by
/// [`tx_schema`](macro@crate::tx_schema) can be defined outside this crate.
#[doc(hidden)]
#[allow(clippy::type_complexity)]
pub enum PreparedOp<'tx, K, V, KEYS, PARAMS, STATE> {
    Get {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        get: Box<dyn Fn(&K, Option<&V>, &PARAMS, &mut STATE) + 'tx>,
    },
    GetOrInsertWith {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        value_generator: Box<dyn Fn(&K, &PARAMS, &mut STATE) -> V + 'tx>,
        get: Box<dyn Fn(&K, &V, &PARAMS, &mut STATE) + 'tx>,
    },
    InsertWith {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        value_generator: Box<dyn Fn(&K, &PARAMS, &mut STATE) -> V + 'tx>,
        take_key: bool,
    },
    InsertWithIfAbsent {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        value_generator: Box<dyn Fn(&K, &PARAMS, &mut STATE) -> V + 'tx>,
        take_key: bool,
    },
    Modify {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        mutate: Box<dyn Fn(&K, &mut V, &PARAMS, &mut STATE) + 'tx>,
    },
    MoveValue {
        key_selector_from: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        key_selector_to: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
    },
    Remove {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
    },
    RemoveIf {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        condition: Box<dyn Fn(&K, &V, &PARAMS, &mut STATE) -> bool + 'tx>,
    },
    SwapValue {
        key_selector_a: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        key_selector_b: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
    },
    Update {
        key_selector: Box<dyn TxKeySelector<TxKey<K>, KEYS> + 'tx>,
        transform: Box<dyn Fn(&K, Option<&V>, &PARAMS, &mut STATE) -> Option<V> + 'tx>,
        take_key: bool,
    },
}

impl<'tx, K, V, KEYS, PARAMS, STATE> PreparedOp<'tx, K, V, KEYS, PARAMS, STATE> {
    pub(crate) fn read_write_bitmasks(&self, keys: &KEYS) -> (BitMask, BitMask) {
        match self {
            Self::Get { key_selector, .. } => {
                (key_selector.get(keys).shard_index.bitmask(), BitMask::ZERO)
            }
            Self::GetOrInsertWith { key_selector, .. }
            | Self::InsertWith { key_selector, .. }
            | Self::InsertWithIfAbsent { key_selector, .. }
            | Self::Modify { key_selector, .. }
            | Self::Remove { key_selector, .. }
            | Self::RemoveIf { key_selector, .. }
            | Self::Update { key_selector, .. } => {
                (BitMask::ZERO, key_selector.get(keys).shard_index.bitmask())
            }
            Self::MoveValue {
                key_selector_from,
                key_selector_to,
                ..
            } => (
                BitMask::ZERO,
                key_selector_from.get(keys).shard_index.bitmask()
                    | key_selector_to.get(keys).shard_index.bitmask(),
            ),
            Self::SwapValue {
                key_selector_a,
                key_selector_b,
                ..
            } => (
                BitMask::ZERO,
                key_selector_a.get(keys).shard_index.bitmask()
                    | key_selector_b.get(keys).shard_index.bitmask(),
            ),
        }
    }
    /// Insert the stable identifiers of all key handles referenced by this op.
    pub(crate) fn insert_key_ids(&self, ids: &mut HashSet<&'static str>) {
        match self {
            Self::Get { key_selector, .. }
            | Self::GetOrInsertWith { key_selector, .. }
            | Self::InsertWith { key_selector, .. }
            | Self::InsertWithIfAbsent { key_selector, .. }
            | Self::Modify { key_selector, .. }
            | Self::Remove { key_selector, .. }
            | Self::RemoveIf { key_selector, .. }
            | Self::Update { key_selector, .. } => {
                ids.insert(key_selector.key_id());
            }
            Self::MoveValue {
                key_selector_from,
                key_selector_to,
                ..
            } => {
                ids.insert(key_selector_from.key_id());
                ids.insert(key_selector_to.key_id());
            }
            Self::SwapValue {
                key_selector_a,
                key_selector_b,
                ..
            } => {
                ids.insert(key_selector_a.key_id());
                ids.insert(key_selector_b.key_id());
            }
        }
    }
}

impl<'tx, K, V, KEYS, PARAMS, STATE> PreparedOp<'tx, K, V, KEYS, PARAMS, STATE>
where
    K: Clone + Hash + Eq,
{
    pub(crate) fn apply<L, S>(
        &self,
        lock_guards: &mut LockGuards<'_, K, V, L>,
        keys: &mut KEYS,
        params: &PARAMS,
        indexer: &Indexer<S>,
        state: &mut STATE,
    ) where
        L: LockPolicy,
        S: BuildHasher,
    {
        match self {
            Self::Get { key_selector, get } => {
                let key = key_selector.get(keys);
                let shard =
                    if (key.shard_index.bitmask() & lock_guards.write_bitmask) != BitMask::ZERO {
                        lock_guards.write_guard(key).deref_mut()
                    } else {
                        lock_guards.read_guard(key).deref()
                    };
                let value_ref = ShardOps::value_ref(shard, key.hash_code, &key.key);
                (get)(&key.key, value_ref, params, state)
            }
            Self::GetOrInsertWith {
                key_selector,
                value_generator,
                get,
            } => {
                let key = key_selector.get(keys);
                let shard = lock_guards.write_guard(key);
                let value_ref = ShardOps::get_or_insert_with(
                    shard,
                    key.hash_code,
                    &key.key,
                    |k| (value_generator)(k, params, state),
                    indexer,
                );
                (get)(&key.key, value_ref, params, state)
            }
            Self::InsertWith {
                key_selector,
                value_generator,
                take_key,
            } => {
                let key = if *take_key {
                    key_selector.take(keys)
                } else {
                    key_selector.get(keys).clone()
                };
                let new_value = (value_generator)(&key.key, params, state);
                let write_guard = lock_guards.write_guard(&key);
                ShardOps::insert::<K, V, S>(
                    write_guard,
                    key.hash_code,
                    key.key,
                    new_value,
                    indexer,
                );
            }
            Self::InsertWithIfAbsent {
                key_selector,
                value_generator,
                take_key,
            } => {
                let key = if *take_key {
                    key_selector.take(keys)
                } else {
                    key_selector.get(keys).clone()
                };
                let write_guard = lock_guards.write_guard(&key);
                ShardOps::insert_if_absent::<K, V, S>(
                    write_guard,
                    key.hash_code,
                    key.key,
                    |k| (value_generator)(k, params, state),
                    indexer,
                );
            }
            Self::Modify {
                key_selector,
                mutate,
            } => {
                let key = key_selector.get(keys);
                let shard = lock_guards.write_guard(key);
                ShardOps::modify(shard, key.hash_code, &key.key, |k, v| {
                    mutate(k, v, params, state)
                });
            }
            Self::MoveValue {
                key_selector_from,
                key_selector_to,
            } => {
                let key_from = key_selector_from.get(keys);
                let key_to = key_selector_to.get(keys);
                MultiShardOps::move_value::<K, V, L, S>(
                    &mut lock_guards.write,
                    key_from,
                    key_to,
                    indexer,
                );
            }
            Self::Remove { key_selector } => {
                let key = key_selector.get(keys);
                let shard = lock_guards.write_guard(key);
                ShardOps::remove_entry::<K, V>(shard, key.hash_code, &key.key);
            }
            Self::RemoveIf {
                key_selector,
                condition,
            } => {
                let key = key_selector.get(keys);
                let shard = lock_guards.write_guard(key);
                ShardOps::remove_if(shard, key.hash_code, &key.key, |k, v| {
                    condition(k, v, params, state)
                });
            }
            Self::SwapValue {
                key_selector_a,
                key_selector_b,
            } => {
                let key_a = key_selector_a.get(keys);
                let key_b = key_selector_b.get(keys);
                MultiShardOps::swap_value::<K, V, L, S>(
                    &mut lock_guards.write,
                    key_a,
                    key_b,
                    indexer,
                );
            }
            Self::Update {
                key_selector,
                transform,
                take_key,
            } => {
                let key = if *take_key {
                    key_selector.take(keys)
                } else {
                    key_selector.get(keys).clone()
                };
                let shard = lock_guards.write_guard(&key);
                ShardOps::update(
                    shard,
                    key.hash_code,
                    key.key,
                    |k, v_opt| transform(k, v_opt, params, state),
                    indexer,
                );
            }
        }
    }
}
