use crate::{
    hasher::DefaultBuildHasher, indexer::Indexer, lock_policies::lock_policy::LockPolicy,
    new_types::ShardCount, prepared::tx_builder::PreparedBuilderPhase, tx_map::TxMap,
};
use std::hash::{BuildHasher, Hash};

/// Schema trait for a prepared transaction.
///
/// Associates the transaction's structural types (key, keys, params, state)
/// with the schema type, as well as the specialised prepared transaction
/// builder and transaction types generated for the schema. Implemented by the
/// [`tx_schema`] macro.
///
/// The map's value type, lock policy and hasher are deliberately *not* part
/// of the schema: they are carried by the specialised
/// [`PreparedTransaction`](Self::PreparedTransaction) itself (with the lock
/// policy and hasher defaulting to `MutexPolicy` and `DefaultBuildHasher`)
/// and are inferred from the map when the transaction is built via
/// [`TxMap::prepared_tx`](crate::tx_map::TxMap::prepared_tx). This keeps the
/// [`tx_schema`] invocation free of any type that describes the map: only the
/// transaction's own keys, params and state are written.
pub trait TxSchema {
    /// The key type of the map the transaction operates on.
    type Key;
    /// The value type of the map the transaction operates on.
    ///
    /// Carried by the schema so the specialised
    /// [`PreparedTransaction`](Self::PreparedTransaction) is generic over the
    /// schema alone: storing one only requires writing the schema with its
    /// key and value types, e.g.
    /// `TransferPreparedTransaction<'tx, Transfer<String, u64>>`.
    type Value;
    /// The raw (un-indexed) keys type.
    ///
    /// Whether it can be hashed into [`IndexedKeys`](Self::IndexedKeys) with
    /// a given hasher is checked when the transaction is executed, since the
    /// hasher belongs to the map rather than the schema.
    type Keys;
    /// The indexed keys type after hashing.
    type IndexedKeys;
    /// The parameters passed on each execution.
    type Params;
    /// The mutable working state (must be `Default`).
    type State: Default;
    /// The specialised prepared transaction builder generated by [`tx_schema`]
    /// for this schema.
    ///
    /// `PHASE` is a phase marker ([`PreparedBuilderPhase`] while the builder
    /// is still accepting guard requirements and
    /// [`PreparedBuildablePhase`](crate::prepared::tx_builder::PreparedBuildablePhase)
    /// once it has at least one operation and can be turned into a
    /// transaction). The lock policy `L` and hasher `S` default to
    /// `MutexPolicy` and `DefaultBuildHasher`.
    type PreparedTxBuilder<'tx, L, S, PHASE>
    where
        Self: 'tx,
        L: LockPolicy + 'tx,
        S: BuildHasher + 'tx,
        PHASE: 'tx;
    /// The specialised prepared transaction generated by [`tx_schema`] for
    /// this schema.
    ///
    /// The lock policy `L` and hasher `S` default to `MutexPolicy` and
    /// `DefaultBuildHasher`, so a transaction can be stored with a single
    /// generic parameter, e.g. `TransferPreparedTransaction<'tx, Transfer<String, u64>>`.
    type PreparedTransaction<'tx, L, S>
    where
        Self: 'tx,
        L: LockPolicy + 'tx,
        S: BuildHasher + 'tx;

    /// Starts building a prepared transaction for this schema on the given
    /// map.
    ///
    /// Every type is inferred from the map, so no generic parameters need to
    /// be written: `Transfer::prepared_tx(&db)` returns the specialised
    /// `TransferPreparedTxBuilder`. [`TxMap::prepared_tx`](crate::tx_map::TxMap::prepared_tx)
    /// delegates to this method.
    fn prepared_tx<'tx, L, S>(
        map: &'tx TxMap<Self::Key, Self::Value, L, S>,
    ) -> Self::PreparedTxBuilder<'tx, L, S, PreparedBuilderPhase>
    where
        Self: Sized + 'tx,
        L: LockPolicy + 'tx,
        S: BuildHasher + 'tx,
        Self::Key: Hash + 'tx,
        Self::Value: 'tx;
}

/// Raw keys that can be hashed into indexed keys.
pub trait TxKeys<K, IndexedKeys, S = DefaultBuildHasher>
where
    S: BuildHasher,
{
    /// Converts raw keys to indexed keys by computing hashes and shard indices.
    fn into_indexed(self, shard_count: ShardCount, indexer: &Indexer<S>) -> IndexedKeys;
}

/// Selects a single key from a set of indexed keys.
///
/// Implemented by key handle types generated by [`tx_schema`].
pub trait TxKeySelector<K, KEYS> {
    /// Returns a reference to the selected key.
    fn get<'keys>(&self, keys: &'keys KEYS) -> &'keys K;
    /// Returns a stable identifier for the selected key handle.
    ///
    /// Used at transaction build time to detect whether a key handle is seen
    /// by a later operation. When the final op to reference a handle is a
    /// consuming operation, the handle is "provably last-used", so its key
    /// can be moved instead of cloned.
    fn key_id(&self) -> &'static str;
    /// Takes the selected key out of the keys container.
    ///
    /// Only safe to call when the handle is provably last-used within the
    /// transaction (see [`key_id`](TxKeySelector::key_id)).
    fn take(&self, keys: &mut KEYS) -> K;
}

#[macro_export]
macro_rules! tx_schema {
    (
        $name:ident,
        keys: [ $($key:ident),* $(,)? ],
        params: { $($param_field:ident: $param_type:ty),* $(,)? },
        state: { $($state_field:ident: $state_type:ty),* $(,)? }
        $(,)?
    ) => {
        $crate::_paste! {
            pub use [<__private $name>] :: $name;
            pub use [<__private $name>] :: [<$name Keys>];
            pub use [<__private $name>] :: [<$name Params>];
            pub use [<__private $name>] :: [<$name State>];
            // Specialised prepared transaction types and entry method.
            pub use [<__private $name>] :: [<$name PreparedTxBuilder>];
            pub use [<__private $name>] :: [<$name PreparedTransaction>];
            #[allow(non_snake_case)]
            mod [<__private $name>] {
                // Bring the types referenced by the macro invocation (params,
                // state) and the crate prelude into scope of this private
                // module.
                #[allow(unused_imports)]
                use super::*;
                #[allow(unused_imports)]
                use $crate::prelude::*;

                // schema
                //
                // The schema is generic over the map's key and value types.
                // The value type is part of the schema so the specialised
                // `PreparedTransaction` is generic over the schema alone and
                // can be stored with a single generic parameter, e.g.
                // `TransferPreparedTransaction<'tx, Transfer<String, u64>>`.
                pub struct $name<K, V> {
                    _phantom: std::marker::PhantomData<(K, V)>,
                }
                impl<K, V> $crate::prelude::TxSchema for $name<K, V>
                where
                    K: std::hash::Hash,
                {
                    type Key = K;
                    type Value = V;
                    type Keys =   [<$name Keys>]<K>;
                    type IndexedKeys = [<$name IndexedKeys>]<K>;
                    type Params = [<$name Params>];
                    type State =  [<$name State>];
                    type PreparedTxBuilder<'tx, L, S, PHASE> =
                        [<$name PreparedTxBuilder>]<'tx, $name<K, V>, L, S, PHASE>
                    where
                        Self: 'tx,
                        L: $crate::prelude::LockPolicy + 'tx,
                        S: std::hash::BuildHasher + 'tx,
                        PHASE: 'tx;
                    type PreparedTransaction<'tx, L, S> =
                        [<$name PreparedTransaction>]<'tx, $name<K, V>, L, S>
                    where
                        Self: 'tx,
                        L: $crate::prelude::LockPolicy + 'tx,
                        S: std::hash::BuildHasher + 'tx;

                    fn prepared_tx<'tx, L, S>(
                        map: &'tx $crate::prelude::TxMap<K, V, L, S>,
                    ) -> [<$name PreparedTxBuilder>]<
                        'tx,
                        $name<K, V>,
                        L,
                        S,
                        $crate::prelude::PreparedBuilderPhase,
                    >
                    where
                        K: std::hash::Hash + 'tx,
                        V: 'tx,
                        L: $crate::prelude::LockPolicy + 'tx,
                        S: std::hash::BuildHasher + 'tx,
                    {
                        [<$name PreparedTxBuilder>] {
                            custodian: &map.custodian,
                            indexer: &map.indexer,
                            guards: std::vec::Vec::new(),
                            ops: std::vec::Vec::new(),
                            _phase: std::marker::PhantomData,
                        }
                    }
                }
                impl<K, V> $name<K, V> {
                    pub const SCHEMA: $name<K, V> = $name {
                        _phantom: std::marker::PhantomData,
                    };
                    /// Starts building a prepared transaction for this schema
                    /// on the given map.
                    ///
                    /// Every type is inferred from the map, so no generic
                    /// parameters need to be written:
                    /// `Transfer::prepared_tx(&db)` returns the specialised
                    /// `TransferPreparedTxBuilder`.
                    pub fn prepared_tx<'tx, L, S>(
                        map: &'tx $crate::prelude::TxMap<K, V, L, S>,
                    ) -> [<$name PreparedTxBuilder>]<
                        'tx,
                        $name<K, V>,
                        L,
                        S,
                        $crate::prelude::PreparedBuilderPhase,
                    >
                    where
                        K: std::hash::Hash + 'tx,
                        V: 'tx,
                        L: $crate::prelude::LockPolicy + 'tx,
                        S: std::hash::BuildHasher + 'tx,
                    {
                        [<$name PreparedTxBuilder>] {
                            custodian: &map.custodian,
                            indexer: &map.indexer,
                            guards: std::vec::Vec::new(),
                            ops: std::vec::Vec::new(),
                            _phase: std::marker::PhantomData,
                        }
                    }
                }
                // Key handles are value-type independent, so they are defined
                // on the `()` value instantiation of the schema. Writing
                // `Transfer::from` therefore never requires naming the map's
                // value type.
                impl<K> $name<K, ()> {
                    $(
                        #[allow(non_upper_case_globals)]
                        pub const $key: [<$name _ $key>]<K> = [<$name _ $key>] {
                            _phantom: std::marker::PhantomData,
                        };
                    )*
                }

                // keys
                pub struct [<$name Keys>]<K> {
                    $(pub $key: K,)*
                }

                // params
                pub struct [<$name Params>] {
                    $(pub $param_field: $param_type,)*
                }

                // state
                #[derive(Debug, Default, Hash, PartialEq, Eq)]
                pub struct [<$name State>] {
                    $(pub $state_field: $state_type,)*
                }

                pub struct [<$name IndexedKeys>]<K> {
                    $(pub $key: std::option::Option<$crate::prelude::TxKey<K>>,)*
                }
                $(
                    #[allow(non_camel_case_types)]
                    pub struct [<$name _ $key>]<K> {
                    _phantom: std::marker::PhantomData<K>,
                    }
                )*
                $(
                    impl<K> $crate::prelude::TxKeySelector<$crate::prelude::TxKey<K>, [<$name IndexedKeys>]<K>> for [<$name _ $key>]<K>
                    {
                        fn get<'keys>(&self, keys: &'keys [<$name IndexedKeys>]<K>) -> &'keys $crate::prelude::TxKey<K> {
                            keys.$key.as_ref().expect("key handle already consumed")
                        }
                        fn key_id(&self) -> &'static str {
                            stringify!($key)
                        }
                        fn take(&self, keys: &mut [<$name IndexedKeys>]<K>) -> $crate::prelude::TxKey<K> {
                            keys.$key.take().expect("key handle already consumed")
                        }
                    }
                )*
                impl<K, S> $crate::prelude::TxKeys<K, [<$name IndexedKeys>]<K>, S> for [<$name Keys>]<K>
                where
                    K: std::hash::Hash,
                    S: std::hash::BuildHasher,
                {
                    fn into_indexed(self, shard_count: $crate::prelude::ShardCount, indexer: &$crate::indexer::Indexer<S>) -> [<$name IndexedKeys>]<K> {
                        [<$name IndexedKeys>] {
                            $(
                                $key: std::option::Option::Some(indexer.indexed_key(shard_count, self.$key)),
                            )*
                        }
                    }
                }

                // Specialised prepared transaction builder.
                //
                // The whole struct and impl are generated by the macro for
                // each schema. The builder is generic over the schema type
                // (so the lock policy and hasher default to `MutexPolicy` and
                // `DefaultBuildHasher` and the phase defaults to
                // `PreparedBuilderPhase`); the schema itself is baked in by
                // the type name.
                pub struct [<$name PreparedTxBuilder>]<
                    'tx,
                    SCHEMA,
                    L = $crate::prelude::MutexPolicy,
                    S = $crate::prelude::DefaultBuildHasher,
                    PHASE = $crate::prelude::PreparedBuilderPhase,
                > where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                {
                    pub(crate) custodian: &'tx $crate::custodian::Custodian<SCHEMA::Key, SCHEMA::Value, L>,
                    pub(crate) indexer: &'tx $crate::indexer::Indexer<S>,
                    #[allow(clippy::type_complexity)]
                    pub(crate) guards: std::vec::Vec<
                        $crate::prepared::guard::Guard<
                            'tx,
                            SCHEMA::Key,
                            SCHEMA::Value,
                            SCHEMA::IndexedKeys,
                            SCHEMA::Params,
                            SCHEMA::State,
                        >,
                    >,
                    #[allow(clippy::type_complexity)]
                    pub(crate) ops: std::vec::Vec<
                        $crate::prepared::op::PreparedOp<
                            'tx,
                            SCHEMA::Key,
                            SCHEMA::Value,
                            SCHEMA::IndexedKeys,
                            SCHEMA::Params,
                            SCHEMA::State,
                        >,
                    >,
                    pub(crate) _phase: std::marker::PhantomData<PHASE>,
                }

                impl<'tx, SCHEMA, L, S>
                    [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuilderPhase>
                where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                {
                    /// Adds a guard precondition using a key selector.
                    pub fn require(
                        mut self,
                        name: impl AsRef<str>,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        condition: impl Fn(
                            &SCHEMA::Key,
                            Option<&SCHEMA::Value>,
                            &SCHEMA::Params,
                            &mut SCHEMA::State,
                        ) -> bool
                        + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuilderPhase> {
                        let guard = $crate::prepared::guard::Guard {
                            name: name.as_ref().into(),
                            key_selector: Box::new(key_selector),
                            condition: Box::new(condition),
                            _phantom: std::marker::PhantomData,
                        };
                        self.guards.push(guard);
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                }

                impl<'tx, SCHEMA, L, S, PHASE>
                    [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, PHASE>
                where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                {
                    /// Reads a value and passes it (or `None`) to the callback.
                    pub fn get(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        get: impl Fn(&SCHEMA::Key, Option<&SCHEMA::Value>, &SCHEMA::Params, &mut SCHEMA::State) + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::Get {
                            key_selector: Box::new(key_selector),
                            get: Box::new(get),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Ensures the key has a value, inserting `value` if the key is absent,
                    /// then passes the resulting value to `get`.
                    ///
                    /// If the key is present, its value is passed to `get` and `value` is
                    /// discarded. If the key is absent, `value` is inserted and then passed
                    /// to `get`. Requires `SCHEMA::Value: Clone` because the transaction is
                    /// re-usable and `value` must be duplicated for each execution that needs
                    /// to insert it.
                    pub fn get_or_insert(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        value: SCHEMA::Value,
                        get: impl Fn(&SCHEMA::Key, &SCHEMA::Value, &SCHEMA::Params, &mut SCHEMA::State) + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase>
                    where
                        SCHEMA::Value: Clone,
                    {
                        self.ops.push($crate::prepared::op::PreparedOp::GetOrInsertWith {
                            key_selector: Box::new(key_selector),
                            value_generator: Box::new(move |_k, _p, _s| value.clone()),
                            get: Box::new(get),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }

                    /// Ensures the key has a value, inserting a generated value if the key is
                    /// absent, then passes the resulting value to `get`.
                    ///
                    /// If the key is present, its value is passed to `get` and
                    /// `value_generator` is never called. If the key is absent,
                    /// `value_generator` is called with the key, params and state and its
                    /// result is inserted and then passed to `get`.
                    pub fn get_or_insert_with(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        value_generator: impl Fn(&SCHEMA::Key, &SCHEMA::Params, &mut SCHEMA::State) -> SCHEMA::Value
                        + 'tx,
                        get: impl Fn(&SCHEMA::Key, &SCHEMA::Value, &SCHEMA::Params, &mut SCHEMA::State) + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::GetOrInsertWith {
                            key_selector: Box::new(key_selector),
                            value_generator: Box::new(value_generator),
                            get: Box::new(get),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }

                    /// Inserts a value generated from the key and parameters.
                    pub fn insert_with(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        value_generator: impl Fn(&SCHEMA::Key, &SCHEMA::Params, &mut SCHEMA::State) -> SCHEMA::Value
                        + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::InsertWith {
                            key_selector: Box::new(key_selector),
                            value_generator: Box::new(value_generator),
                            take_key: false,
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Inserts a value only if the key is absent.
                    pub fn insert_with_if_absent(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        value_generator: impl Fn(&SCHEMA::Key, &SCHEMA::Params, &mut SCHEMA::State) -> SCHEMA::Value
                        + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::InsertWithIfAbsent {
                            key_selector: Box::new(key_selector),
                            value_generator: Box::new(value_generator),
                            take_key: false,
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Mutates an existing value in-place.
                    pub fn modify(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        mutate: impl Fn(&SCHEMA::Key, &mut SCHEMA::Value, &SCHEMA::Params, &mut SCHEMA::State) + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::Modify {
                            key_selector: Box::new(key_selector),
                            mutate: Box::new(mutate),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Moves a value from one key to another atomically.
                    pub fn move_value(
                        mut self,
                        key_selector_from: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        key_selector_to: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::MoveValue {
                            key_selector_from: Box::new(key_selector_from),
                            key_selector_to: Box::new(key_selector_to),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Removes a key-value pair.
                    pub fn remove(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::Remove {
                            key_selector: Box::new(key_selector),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Removes a key if the condition is satisfied.
                    pub fn remove_if(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        condition: impl Fn(&SCHEMA::Key, &SCHEMA::Value, &SCHEMA::Params, &mut SCHEMA::State) -> bool
                        + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::RemoveIf {
                            key_selector: Box::new(key_selector),
                            condition: Box::new(condition),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Swaps the values of two keys atomically.
                    pub fn swap_value(
                        mut self,
                        key_selector_a: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        key_selector_b: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::SwapValue {
                            key_selector_a: Box::new(key_selector_a),
                            key_selector_b: Box::new(key_selector_b),
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                    /// Updates or removes an entry via a transform closure.
                    pub fn update(
                        mut self,
                        key_selector: impl $crate::prelude::TxKeySelector<$crate::prelude::TxKey<SCHEMA::Key>, SCHEMA::IndexedKeys> + 'tx,
                        transform: impl Fn(
                            &SCHEMA::Key,
                            Option<&SCHEMA::Value>,
                            &SCHEMA::Params,
                            &mut SCHEMA::State,
                        ) -> Option<SCHEMA::Value>
                        + 'tx,
                    ) -> [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase> {
                        self.ops.push($crate::prepared::op::PreparedOp::Update {
                            key_selector: Box::new(key_selector),
                            transform: Box::new(transform),
                            take_key: false,
                        });
                        [<$name PreparedTxBuilder>] {
                            custodian: self.custodian,
                            indexer: self.indexer,
                            guards: self.guards,
                            ops: self.ops,
                            _phase: std::marker::PhantomData,
                        }
                    }
                }

                impl<'tx, SCHEMA, L, S>
                    [<$name PreparedTxBuilder>]<'tx, SCHEMA, L, S, $crate::prelude::PreparedBuildablePhase>
                where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                    SCHEMA::Key: Clone + std::hash::Hash + Eq,
                    SCHEMA::Keys: $crate::prelude::TxKeys<SCHEMA::Key, SCHEMA::IndexedKeys, S>,
                {
                    #[must_use]
                    /// Consumes the builder and returns a
                    /// [`PreparedTransaction`](crate::prepared::transaction::PreparedTransaction)
                    /// (the specialised `$name PreparedTransaction` generated by
                    /// [`tx_schema`](macro@crate::tx_schema)).
                    ///
                    /// The transaction carries the entire execution plan — the map
                    /// references, guards and operations — as its own fields, so no
                    /// closure needs to be boxed. The returned transaction can be
                    /// executed repeatedly and stored easily.
                    pub fn into_transaction(self) -> [<$name PreparedTransaction>]<'tx, SCHEMA, L, S> {
                        // Ops apply in order, so a consuming op may move its key out of the
                        // per-execution keys container instead of cloning it only when no
                        // later op references the same key handle. Iterating backwards and
                        // keeping the handles already seen by later ops, the final op to see
                        // a key always takes it; earlier uses fall back to cloning.
                        let mut taken: std::collections::HashSet<&'static str> = std::collections::HashSet::new();
                        let mut ops = self.ops;
                        for op in ops.iter_mut().rev() {
                            match op {
                                $crate::prepared::op::PreparedOp::InsertWith {
                                    key_selector,
                                    take_key,
                                    ..
                                }
                                | $crate::prepared::op::PreparedOp::InsertWithIfAbsent {
                                    key_selector,
                                    take_key,
                                    ..
                                }
                                | $crate::prepared::op::PreparedOp::Update {
                                    key_selector,
                                    take_key,
                                    ..
                                } => {
                                    *take_key = taken.insert(key_selector.key_id());
                                }
                                _ => {}
                            }
                            op.insert_key_ids(&mut taken);
                        }
                        let [<$name PreparedTxBuilder>] {
                            custodian,
                            indexer,
                            guards,
                            ..
                        } = self;
                        [<$name PreparedTransaction>] {
                            custodian,
                            indexer,
                            guards,
                            ops,
                        }
                    }
                }

                // Specialised prepared transaction.
                //
                // The whole struct and impl are generated by the macro for
                // each schema. The transaction is generic over the schema
                // type; the lock policy and hasher default to `MutexPolicy`
                // and `DefaultBuildHasher`, so it is storable with a single
                // generic parameter:
                // `TransferPreparedTransaction<'tx, Transfer<String, u64>>`.
                pub struct [<$name PreparedTransaction>]<
                    'tx,
                    SCHEMA,
                    L = $crate::prelude::MutexPolicy,
                    S = $crate::prelude::DefaultBuildHasher,
                > where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                {
                    pub(crate) custodian: &'tx $crate::custodian::Custodian<SCHEMA::Key, SCHEMA::Value, L>,
                    pub(crate) indexer: &'tx $crate::indexer::Indexer<S>,
                    #[allow(clippy::type_complexity)]
                    pub(crate) guards: std::vec::Vec<
                        $crate::prepared::guard::Guard<
                            'tx,
                            SCHEMA::Key,
                            SCHEMA::Value,
                            SCHEMA::IndexedKeys,
                            SCHEMA::Params,
                            SCHEMA::State,
                        >,
                    >,
                    #[allow(clippy::type_complexity)]
                    pub(crate) ops: std::vec::Vec<
                        $crate::prepared::op::PreparedOp<
                            'tx,
                            SCHEMA::Key,
                            SCHEMA::Value,
                            SCHEMA::IndexedKeys,
                            SCHEMA::Params,
                            SCHEMA::State,
                        >,
                    >,
                }

                impl<'tx, SCHEMA, L, S> [<$name PreparedTransaction>]<'tx, SCHEMA, L, S>
                where
                    SCHEMA: $crate::prelude::TxSchema + 'tx,
                    L: $crate::prelude::LockPolicy,
                    S: std::hash::BuildHasher,
                    SCHEMA::Key: Clone + std::hash::Hash + Eq,
                    SCHEMA::Keys: $crate::prelude::TxKeys<SCHEMA::Key, SCHEMA::IndexedKeys, S>,
                {
                    #[must_use]
                    /// Executes the transaction with the given keys and parameters.
                    ///
                    /// The keys are hashed, locks are acquired, guards are checked,
                    /// and operations are applied. Returns the final state wrapped in
                    /// [`TxResult`](crate::prelude::TxResult).
                    pub fn execute(&self, keys: SCHEMA::Keys, params: SCHEMA::Params) -> $crate::prelude::TxResult<SCHEMA::State> {
                        let mut keys = keys.into_indexed(self.custodian.shard_count, self.indexer);
                        let mut total_read_bitmask = $crate::new_types::BitMask::ZERO;
                        let mut total_write_bitmask = $crate::new_types::BitMask::ZERO;

                        // get all bitmasks
                        for guard in self.guards.iter() {
                            total_read_bitmask |= guard.read_bitmask(&keys);
                        }
                        for op in self.ops.iter() {
                            let (read_bitmask, write_bitmask) = op.read_write_bitmasks(&keys);
                            total_read_bitmask |= read_bitmask;
                            total_write_bitmask |= write_bitmask;
                        }
                        // ensure locks are either read or write, not both
                        total_read_bitmask &= !total_write_bitmask;

                        let mut lock_guards = self
                            .custodian
                            .lock_guards(total_read_bitmask, total_write_bitmask);
                        let mut state = SCHEMA::State::default();
                        for (i, guard) in self.guards.iter().enumerate() {
                            if !guard.is_condition_met::<L>(&mut lock_guards, &keys, &params, &mut state) {
                                return $crate::prelude::TxResult::RequirementNotMet {
                                    index: i,
                                    requirement: guard.name.clone(),
                                    state,
                                };
                            }
                        }
                        for op in self.ops.iter() {
                            op.apply::<L, S>(
                                &mut lock_guards,
                                &mut keys,
                                &params,
                                self.indexer,
                                &mut state,
                            );
                        }
                        $crate::prelude::TxResult::Completed { state }
                    }
                }
            }
        }
    };
}

pub use tx_schema;
