//! Prepared (re-usable) transactions.
//!
//! The specialised `PreparedTransaction` type for each schema is generated by
//! the [`tx_schema`](macro@crate::tx_schema) macro (e.g.
//! `TransferPreparedTransaction`) and added as an associated type of
//! [`TxSchema`](crate::prepared::schema::TxSchema).
//!
//! A prepared transaction is built via
//! [`TxMap::prepared_tx`](crate::tx_map::TxMap::prepared_tx) or the schema's
//! specialised `prepared_tx` method (e.g. `Transfer::prepared_tx`), and can
//! be executed multiple times with different keys and parameters. The
//! transaction plan (which shards to lock and which operations to apply) is
//! determined at build time and stored directly in the transaction, so no
//! function needs to be boxed.
//!
//! The transaction is generic over the schema alone, making it easy to store
//! in structs, collections, or behind an `Arc` with a single generic
//! parameter:
//!
//! ```
//! use txmap::prelude::*;
//!
//! tx_schema! {
//!     Demo,
//!     keys: [key],
//!     params: {},
//!     state: {},
//! }
//!
//! struct App<'tx> {
//!     demo: DemoPreparedTransaction<'tx, Demo<String, u64>>,
//! }
//! ```
//!
//! The schema carries the map's key and value types, so storing a transaction
//! only requires writing the schema with those types. The lock policy and
//! hasher default to `MutexPolicy` and `DefaultBuildHasher`.
