use crate::{
    custodian::Custodian,
    indexer::Indexer,
    lock_policies::lock_policy::LockPolicy,
    new_types::BitMask,
    prepared::{guard::Guard, op::PreparedOp, schema::TxKeys},
    result::TxResult,
};
use std::hash::{BuildHasher, Hash};

/// Runs the execution plan of a prepared transaction.
///
/// The keys are hashed, locks are acquired, guards are checked, and
/// operations are applied. Returns the final state wrapped in [`TxResult`].
///
/// Called by the schema-specific transaction type generated by the
/// [`tx_schema`](macro@crate::tx_schema) macro, which holds the concrete
/// `KEYS`/`PARAMS`/`STATE` types.
pub fn execute<'tx, K, V, L, S, KEYS, PARAMS, STATE, RAW>(
    custodian: &Custodian<K, V, L>,
    indexer: &Indexer<S>,
    guards: &[Guard<'tx, K, V, KEYS, PARAMS, STATE>],
    ops: &[PreparedOp<'tx, K, V, KEYS, PARAMS, STATE>],
    keys: RAW,
    params: PARAMS,
) -> TxResult<STATE>
where
    K: Clone + Hash + Eq,
    L: LockPolicy,
    S: BuildHasher,
    STATE: Default,
    RAW: TxKeys<K, KEYS, S>,
{
    let mut keys = keys.into_indexed(custodian.shard_count, indexer);
    let mut total_read_bitmask = BitMask::ZERO;
    let mut total_write_bitmask = BitMask::ZERO;

    // get all bitmasks
    for guard in guards.iter() {
        total_read_bitmask |= guard.read_bitmask(&keys);
    }
    for op in ops.iter() {
        let (read_bitmask, write_bitmask) = op.read_write_bitmasks(&keys);
        total_read_bitmask |= read_bitmask;
        total_write_bitmask |= write_bitmask;
    }
    // ensure locks are either read or write, not both
    total_read_bitmask &= !total_write_bitmask;

    let mut lock_guards = custodian.lock_guards(total_read_bitmask, total_write_bitmask);
    let mut state = STATE::default();
    for (i, guard) in guards.iter().enumerate() {
        if !guard.is_condition_met::<L>(&mut lock_guards, &keys, &params, &mut state) {
            return TxResult::RequirementNotMet {
                index: i,
                requirement: guard.name.clone(),
                state,
            };
        }
    }
    for op in ops.iter() {
        op.apply::<L, S>(&mut lock_guards, &mut keys, &params, indexer, &mut state);
    }
    TxResult::Completed { state }
}
