//! Prepared (re-usable) transactions are built with a fluent builder that is
//! generated by the [`tx_schema`](macro@crate::tx_schema) macro for each
//! schema.
//!
//! The macro generates a specialised builder type per schema (e.g.
//! `TransferPreparedTxBuilder`), along with a specialised transaction type
//! (e.g. `TransferPreparedTransaction`), and adds both as associated types of
//! [`TxSchema`](crate::prepared::schema::TxSchema). Start with
//! [`TxMap::prepared_tx`](crate::tx_map::TxMap::prepared_tx) or the schema's
//! specialised `prepared_tx` method (e.g. `Transfer::prepared_tx`), add guard
//! requirements with `require`, add operations (e.g. `modify`), then call
//! `into_transaction` to obtain a transaction that can be executed repeatedly.
//!
//! The builder uses a phase marker generic to enforce, at compile time, that
//! `into_transaction` can only be called once the builder has at least one
//! operation:
//!
//! - [`PreparedBuilderPhase`]: the builder is still accepting guard
//!   requirements and has no operations yet.
//! - [`PreparedBuildablePhase`]: the builder has at least one operation and
//!   can be turned into a transaction.

/// Phase marker: transaction is still accepting guard requirements.
pub struct PreparedBuilderPhase;
/// Phase marker: transaction has at least one operation and can be built.
pub struct PreparedBuildablePhase;
